# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [24]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [25]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [26]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [27]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0


## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [28]:
from sklearn.model_selection import train_test_split
X = data.drop(['MEDV'], axis=1)
y = data['MEDV']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=42)
print(X_train)
print(y_train)

         CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
295   0.12932   0.0  13.92     0  0.437  ...    4  289.0     16.0  396.90   6.27
462   6.65492   0.0  18.10     0  0.713  ...   24  666.0     20.2  396.90  13.99
251   0.21409  22.0   5.86     0  0.431  ...    7  330.0     19.1  377.07   3.59
494   0.27957   0.0   9.69     0  0.585  ...    6  391.0     19.2  396.90  13.59
464   7.83932   0.0  18.10     0  0.655  ...   24  666.0     20.2  396.90  13.22
..        ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
106   0.17120   0.0   8.56     0  0.520  ...    5  384.0     20.9  395.67  18.66
270   0.29916  20.0   6.96     0  0.464  ...    3  223.0     18.6  388.65  13.00
348   0.01501  80.0   2.01     0  0.435  ...    4  280.0     17.0  390.94   5.99
435  11.16040   0.0  18.10     0  0.740  ...   24  666.0     20.2  109.85  23.27
102   0.22876   0.0   8.56     0  0.520  ...    5  384.0     20.9   70.80  10.63

[101 rows x 13 columns]
295

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [29]:
from sklearn.linear_model import LinearRegression

model = LinearRegression().fit(X_train, y_train)
y_test_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)
print(y_test_pred)
print(y_train_pred)

[27.01908587 36.39926682 19.52223675 25.26810254 19.46487293 23.79870856
 17.18010037 16.20711737 23.68847101 20.04220179 26.36855152 18.59327186
 -6.4664329  22.95909013 17.40686932 27.43257758 19.92666616  6.58724548
 39.32182162 17.90432857 26.00668515 28.80570525 10.37477062 22.76021909
 17.92978821 16.18952859 23.71007322 15.54932536 23.46234325 18.71440048
 20.59025588 23.73922927 25.63449    16.74323723 18.1406512  17.2356924
 29.84079468 17.83161727 25.38606905 25.27635836 14.07970302 28.90885816
 41.21058241 17.56791799 25.57994553 17.0569498  12.4612     26.53317464
 21.41130736 28.45234887 20.77316517 32.93038487 14.8266904  25.19421146
 38.17415252 23.98854895 19.05440652 30.50321095 23.82730866 12.46879907
 21.54510185 28.72042986 30.44440582 14.78885693 20.44691982 17.92921098
 20.86597534 24.75293069 28.72257558 12.63787816 20.1411482  28.1057868
 11.65702628 14.19165287 24.75186273  5.83196668 20.30811648 39.93498257
 19.24440243 14.04250028 20.77083945 14.64620923 20.9

## 3. Calculate and print R-squared for both the training and the testing set.

In [30]:
from sklearn.metrics import r2_score

r2_test = r2_score(y_test, y_test_pred)
r2_train = r2_score(y_test, y_test_pred)
print(r2_test)
print(r2_train)

0.7079608143498456
0.7079608143498456


## 4. Calculate and print mean squared error for both the training and the testing set.

In [31]:
import numpy as np

print("Residual sum of squares test (MSE): ", np.mean((y_test_pred - y_test) ** 2))
print("Residual sum of squares train (MSE): ", np.mean((y_train_pred - y_train) ** 2))

Residual sum of squares test (MSE):  25.564048911173554
Residual sum of squares train (MSE):  19.53653493678433


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [32]:
print("Mean absolute error test: ", np.mean(np.absolute(y_test_pred - y_test)))
print("Mean absolute error train: ",np.mean(np.absolute(y_train_pred - y_train)))

Mean absolute error test:  3.54191503447128
Mean absolute error train:  2.9952565145042116


## Classification Model Evaluation

In [33]:
from sklearn.datasets import load_iris
data = load_iris()

In [34]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [35]:
column_names = data.feature_names

In [36]:
df = pd.DataFrame(data['data'],columns=column_names)

In [37]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [38]:
target = pd.DataFrame(data.target)

In [39]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [40]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [41]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, train_size=0.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [42]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression().fit(X_train, y_train)
y_test_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)
print(y_train_pred)
print(y_test_pred)

[1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2
 1 1 2 1 0 1 2 0 0 1 2 0 2 0 0 2 1 2 2 2 2 1 0 0 1 2 0 0 0 1 2 0 2 2 0 1 1
 2 1 2 0 2 1 2 1 1]


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [43]:
from sklearn.metrics import accuracy_score

accuracy_test = accuracy_score(y_test, y_test_pred)
accuracy_train = accuracy_score(y_train, y_train_pred)
print(accuracy_train)
print(accuracy_test)

1.0
0.9666666666666667


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [44]:
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_test = balanced_accuracy_score(y_test, y_test_pred)
balanced_accuracy_train = balanced_accuracy_score(y_train, y_train_pred)
print(balanced_accuracy_train)
print(balanced_accuracy_test)

1.0
0.9655870445344129


## 10. Calculate and print the precision score for both the training and the testing set.

In [45]:
from sklearn.metrics import precision_score

precission_test = precision_score(y_test, y_test_pred, average='weighted')
precission_train = precision_score(y_train, y_train_pred, average='weighted')
print(precission_train)
print(precission_test)

1.0
0.9674662162162162


## 11. Calculate and print the recall score for both the training and the testing set.

In [46]:
from sklearn.metrics import recall_score

recall_test = recall_score(y_test, y_test_pred, average='weighted')
recall_train = recall_score(y_train, y_train_pred, average='weighted')
print(recall_train)
print(recall_test)

1.0
0.9666666666666667


## 12. Calculate and print the F1 score for both the training and the testing set.

In [47]:
from sklearn.metrics import f1_score

f1_test = f1_score(y_test, y_test_pred, average='weighted')
f1_train = f1_score(y_train, y_train_pred, average='weighted')
print(f1_train)
print(f1_test)

1.0
0.966655420602789


## 13. Generate confusion matrices for both the training and the testing set.

In [48]:
from sklearn.metrics import confusion_matrix

confusion_matrix_test = confusion_matrix(y_test, y_test_pred)
confusion_matrix_train = confusion_matrix(y_train, y_train_pred)
print(confusion_matrix_train)
print(confusion_matrix_test)

[[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]]
[[43  0  0]
 [ 0 36  3]
 [ 0  1 37]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [49]:
from sklearn.dummy import DummyRegressor
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_absolute_error
import xgboost as xgb

models = {
    'Baseline': DummyRegressor(strategy='mean'),
    'Linear regression': LinearRegression(),
    'Polynomial regression deg=1': Pipeline([
        ('scaler', StandardScaler()),
        ("poly_features", PolynomialFeatures(degree=1)),
        ("lin_reg", LinearRegression())
    ]),
    'Polynomial regression deg=2': Pipeline([
        ('scaler', StandardScaler()),
        ("poly_features", PolynomialFeatures(degree=2)),
        ("lin_reg", LinearRegression())
    ]),
    'Polynomial regression deg=3': Pipeline([
        ('scaler', StandardScaler()),
        ("poly_features", PolynomialFeatures(degree=3)),
        ("lin_reg", LinearRegression())
    ]),
    'Xboost': xgb.XGBRegressor(objective='reg:squarederror', random_state=42)
}

results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results.append({
        'Model': name,
        'MAE': mean_absolute_error(y_test, y_pred),
        'R²': r2_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
print(results_df.sort_values('R²', ascending=False))

                         Model       MAE        R²
1            Linear regression  0.182765  0.913188
2  Polynomial regression deg=1  0.182765  0.913188
3  Polynomial regression deg=2  0.181634  0.900384
5                       Xboost  0.075180  0.888640
0                     Baseline  0.736111 -0.064466
4  Polynomial regression deg=3  1.142506 -4.615610


### Linear regression and Polynomial regression degree 1 has the same and the best values with the best performance