# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [10]:
print(data.shape)
print(data.head())


(506, 14)
      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2  


## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, balanced_accuracy_score
from sklearn.datasets import make_regression, make_classification

X = data.drop(columns=['MEDV'])
y = data['MEDV']

X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=.2, random_state=42 )

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [19]:
reg_model = LinearRegression().fit(X_train, y_train)

train_preds = reg_model.predict(X_train)
test_preds = reg_model.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [23]:
print(f"R2 score for training set: {r2_score(y_train, train_preds):.4f}")
print(f"R2 score for test set: {r2_score(y_test, test_preds):.4f}")

R2 score for training set: 0.7509
R2 score for test set: 0.6688


## 4. Calculate and print mean squared error for both the training and the testing set.

In [27]:
print(f"Mean squared error for training set: {mean_squared_error(y_train, train_preds):.4f}")
print(f"Mean squared error for test set: {mean_squared_error(y_test, test_preds):.4f}")

Mean squared error for training set: 21.6414
Mean squared error for test set: 24.2911


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [30]:
print(f"Mean Absolute Error training set: {mean_absolute_error(y_train, train_preds):.4f}")
print(f"Mean Absolute Error test set: {mean_absolute_error(y_test, test_preds):.4f}")

Mean Absolute Error training set: 3.3148
Mean Absolute Error test set: 3.1891


## Classification Model Evaluation

In [31]:
from sklearn.datasets import load_iris
data = load_iris()

In [32]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [33]:
column_names = data.feature_names

In [34]:
df = pd.DataFrame(data['data'],columns=column_names)

In [35]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [36]:
target = pd.DataFrame(data.target)

In [37]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [45]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [49]:
X_c = df
y_c = target

X_train, X_test, y_train, y_test = train_test_split(X_c,y_c, test_size=.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [50]:
cls_model = LogisticRegression().fit(X_train, y_train)


train_preds_c = cls_model.predict(X_train)
test_preds_c = cls_model.predict(X_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [60]:
print(f"Train Accuracy:{accuracy_score(y_train, train_preds_c):.4f}")
print(f"Test Accuracy:{accuracy_score(y_test, test_preds_c):.4f}")


Train Accuracy:0.9750
Test Accuracy:1.0000


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [56]:
print(f"Train Balanced Accuracy: {balanced_accuracy_score(y_train, train_preds_c):.4f}")
print(f"Test Balanced Accuracy: {balanced_accuracy_score(y_test, test_preds_c):.4f}")

Train Balanced Accuracy: 0.9756
Test Balanced Accuracy: 1.0000


## 10. Calculate and print the precision score for both the training and the testing set.

In [55]:
print(f"Train Precision (Macro): {precision_score(y_train, train_preds_c, average='macro'):.4f}")
print(f"Test Precision (Macro): {precision_score(y_test, test_preds_c, average='macro'):.4f}")

Train Precision (Macro): 0.9762
Test Precision (Macro): 1.0000


## 11. Calculate and print the recall score for both the training and the testing set.

In [58]:
print(f"Train Recall (Macro):    {recall_score(y_train, train_preds_c, average='macro'):.4f}")
print(f"Test Recall (Macro):    {recall_score(y_test, test_preds_c, average='macro'):.4f}")

Train Recall (Macro):    0.9756
Test Recall (Macro):    1.0000


## 12. Calculate and print the F1 score for both the training and the testing set.

In [59]:
print(f"Train F1 Score (Macro):  {f1_score(y_train, train_preds_c, average='macro'):.4f}")
print(f"Test F1 Score (Macro):  {f1_score(y_test, test_preds_c, average='macro'):.4f}")

Train F1 Score (Macro):  0.9750
Test F1 Score (Macro):  1.0000


## 13. Generate confusion matrices for both the training and the testing set.

In [61]:
print("Train Confusion Matrix:\n", confusion_matrix(y_train, train_preds_c))
print("Test Confusion Matrix:\n", confusion_matrix(y_test, test_preds_c))

Train Confusion Matrix:
 [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]
Test Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !