# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [509]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [511]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [512]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [513]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [515]:
# Your code here :
# Create a dataframe with only the labels
labels = data['MEDV']

# Create a dataframe with only the features
features = data.drop(columns='MEDV')

# Slit the data into training and testing sets (20 %)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state = 0)


## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [517]:
# Your code here :
# Import the method
from sklearn.linear_model import LinearRegression

# Initialize the model
medv_model = LinearRegression()

# Train the model
medv_model.fit(X_train,y_train)


# Generate predictions on test data
pred_test = medv_model.predict(X_test)

# Generate predictions on training data
pred_train = medv_model.predict(X_train)


## 3. Calculate and print R-squared for both the training and the testing set.

In [519]:
# Your code here :
from sklearn.metrics import r2_score
r2_train = r2_score(y_train, pred_train)
r2_test = r2_score(y_test, pred_test)

print("R2 score on training data;", r2_train )
print("R2 score on test data:", r2_test)

R2 score on training data; 0.7730135569264233
R2 score on test data: 0.5892223849182519


## 4. Calculate and print mean squared error for both the training and the testing set.

In [521]:
# Your code here :
import numpy as np
# I will try to do it by hand:
# for the Training data
print("MSE train calculated by hand:", ((np.array(y_train) - np.array(pred_train))**2).mean())
print("MSE test calculated by hand:", ((np.array(y_test) - np.array(pred_test))**2).mean())

# Let's confirm it using the formula
from sklearn.metrics import mean_squared_error
mse_train = mean_squared_error(y_train, pred_train)
mse_test = mean_squared_error(y_test, pred_test)
print("MSE train calculated using formula:",mse_train)
print("MSE train calculated using formula:",mse_test)


MSE train calculated by hand: 19.32647020358573
MSE test calculated by hand: 33.44897999767644
MSE train calculated using formula: 19.32647020358573
MSE train calculated using formula: 33.44897999767644


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [523]:
# Your code here :
from sklearn.metrics import mean_absolute_error
mae_train = mean_absolute_error(y_train, pred_train)
mae_test = mean_absolute_error(y_test, pred_test)

print("MAE train calculated using formula:",mae_train)
print("MAE train calculated using formula:",mae_test)


MAE train calculated using formula: 3.103156396579435
MAE train calculated using formula: 3.842909220444501


## Classification Model Evaluation

In [525]:
from sklearn.datasets import load_iris
data = load_iris()

In [526]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [527]:
column_names = data.feature_names

In [528]:
df = pd.DataFrame(data['data'],columns=column_names)

In [529]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [530]:
target = pd.DataFrame(data.target)
target

0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [531]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [532]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [534]:
# Your code here :
# Create a dataframe for features and other for target/labels

labels = pd.Series(data['target'], name='labels')

features = pd.DataFrame(data['data'], columns = data['feature_names'])


# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [536]:
# Your code here :
from sklearn.linear_model import LogisticRegression

# Initialize the model
iris_model = LogisticRegression()

# Train the model
iris_model.fit(X_train, y_train)

# Make predictions on test data
pred_test = iris_model.predict(X_test)

# Make predictions on train data
pred_train = iris_model.predict(X_train)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [538]:
# Your code here :
from sklearn.metrics import accuracy_score
# Accuracy score for test set
accur_test = iris_model.score(X_test,y_test)#accuracy_score(y_test,pred_test)

# Accuracy score for training set
accur_train = iris_model.score(X_train,y_train)#accuracy_score(y_train,pred_train)

print("Accuracy score on train data:", accur_train)
print("Accuracy score on test data:", accur_test)

Accuracy score on train data: 0.9916666666666667
Accuracy score on test data: 0.9333333333333333


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [540]:
# Your code here :
from sklearn.metrics import balanced_accuracy_score

train_balanced_accuracy = balanced_accuracy_score(y_train, pred_train)
test_balanced_accuracy = balanced_accuracy_score(y_test, pred_test)

print("Balanced Accuracy score on train data:", train_balanced_accuracy)
print("Balanced Accuracy score on test data:", test_balanced_accuracy)

Balanced Accuracy score on train data: 0.9922480620155039
Balanced Accuracy score on test data: 0.9047619047619048


## 10. Calculate and print the precision score for both the training and the testing set.

In [545]:
# Your code here :
from sklearn.metrics import precision_score
# Calculate macro precision
precision_train = precision_score(y_train, pred_train, average='micro')
precision_test = precision_score(y_test, pred_test, average = 'micro')
print(f'Precision Train: {precision_train:.2f}')
print(f'Precision Test: {precision_test:.2f}')

Precision Train: 0.99
Precision Test: 0.93


## 11. Calculate and print the recall score for both the training and the testing set.

In [549]:
# Your code here :
from sklearn.metrics import recall_score

# Calculate recall
recall_train = recall_score(y_train, pred_train, average='micro')
recall_test = recall_score(y_test, pred_test, average='micro')

print("Recall score on train data:", recall_train)
print("Recall score on test data:", recall_test)


Recall score on train data: 0.9916666666666667
Recall score on test data: 0.9333333333333333


## 12. Calculate and print the F1 score for both the training and the testing set.

In [553]:
# Your code here :
from sklearn.metrics import f1_score

# Calculate f1 score
f1_train = f1_score(y_train, pred_train, average='micro')
f1_test = f1_score(y_test, pred_test, average='micro')

print("f1 score on train data:", f1_train)
print("f1 score on test data:", f1_test)

f1 score on train data: 0.9916666666666667
f1 score on test data: 0.9333333333333333


## 13. Generate confusion matrices for both the training and the testing set.

In [561]:
# Your code here :
from sklearn.metrics import confusion_matrix

# Calculate f1 score
cm_train = confusion_matrix(y_train, pred_train)
cm_test = confusion_matrix(y_test, pred_test)

print(cm_train)
print(cm_test)

[[41  0  0]
 [ 0 42  1]
 [ 0  0 36]]
[[ 9  0  0]
 [ 0  5  2]
 [ 0  0 14]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !